// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const HAS_SUPABASE_CONFIG = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
const MOCK_DB_KEY = "eduport-mock-db";
const MOCK_SESSION_KEY = "eduport-mock-session";

const defaultMockDb = () => ({
  profiles: [
    {
      id: "demo-profile",
      user_id: "demo-user",
      prenom: "Nour",
      nom: "Ben Ali",
      email: "demo@eduport.tn",
      filiere: "GL",
      niveau: "L3",
      cin: "00000000",
      telephone: "+216 00 000 000",
      bio: "Mode demo local",
      date_naissance: "2002-04-20",
    },
    {
      id: "demo-prof-1",
      user_id: "demo-prof-1",
      prenom: "Amina",
      nom: "Trabelsi",
      email: "amina.trabelsi@eduport.tn",
      filiere: "GL",
      niveau: "Professeur",
      bureau: "B12",
      subjects: [{ nom: "Algorithmique", code: "ALG301" }],
    },
    {
      id: "demo-prof-2",
      user_id: "demo-prof-2",
      prenom: "Youssef",
      nom: "Haddad",
      email: "youssef.haddad@eduport.tn",
      filiere: "GL",
      niveau: "Professeur",
      bureau: "C04",
      subjects: [{ nom: "Reseaux", code: "RNV302" }],
    },
    {
      id: "demo-admin",
      user_id: "demo-admin",
      prenom: "Sara",
      nom: "Mansouri",
      email: "sara.mansouri@eduport.tn",
      filiere: "GL",
      niveau: "Admin",
    },
  ],
  user_roles: [
    { user_id: "demo-user", role: "student" },
    { user_id: "demo-prof-1", role: "professor" },
    { user_id: "demo-prof-2", role: "professor" },
    { user_id: "demo-admin", role: "admin" },
  ],
  grades: [
    {
      id: "grade-1",
      student_id: "demo-profile",
      note: 17.5,
      poids: 1,
      type: "DS",
      date_evaluation: "2026-03-10",
      subjects: { id: "alg-301", nom: "Algorithmique", code: "ALG301", coefficient: 3, semestre: "S5", filiere: "GL" },
    },
    {
      id: "grade-2",
      student_id: "demo-profile",
      note: 14.8,
      poids: 1,
      type: "TP",
      date_evaluation: "2026-03-15",
      subjects: { id: "bdd-302", nom: "Bases de donnees", code: "BDD302", coefficient: 2, semestre: "S5", filiere: "GL" },
    },
    {
      id: "grade-3",
      student_id: "demo-profile",
      note: 13.2,
      poids: 1,
      type: "Examen",
      date_evaluation: "2026-03-22",
      subjects: { id: "rnv-303", nom: "Reseaux", code: "RNV303", coefficient: 2, semestre: "S5", filiere: "GL" },
    },
  ],
  schedule: [
    { id: "sched-1", filiere: "GL", jour: 1, heure_debut: "08:00:00", heure_fin: "10:00:00", type_seance: "CM", salle: "A101", subjects: { nom: "Algorithmique", code: "ALG301" } },
    { id: "sched-2", filiere: "GL", jour: 1, heure_debut: "10:30:00", heure_fin: "12:30:00", type_seance: "TD", salle: "B204", subjects: { nom: "Bases de donnees", code: "BDD302" } },
    { id: "sched-3", filiere: "GL", jour: 3, heure_debut: "14:00:00", heure_fin: "16:00:00", type_seance: "TP", salle: "Lab 2", subjects: { nom: "Reseaux", code: "RNV303" } },
  ],
  document_requests: [
    {
      id: "doc-1",
      student_id: "demo-profile",
      type: "attestation_inscription",
      motif: "Pour mon stage",
      statut: "en_attente",
      created_at: new Date().toISOString(),
      decision_ia: null,
      pdf_url: null,
      reviewed_at: null,
      profiles: { prenom: "Nour", nom: "Ben Ali", filiere: "GL" },
    },
  ],
});

const loadMockDb = () => {
  if (typeof window === "undefined") return defaultMockDb();
  try {
    const raw = window.localStorage.getItem(MOCK_DB_KEY);
    if (raw) return JSON.parse(raw);
  } catch {
    // Fall through to the default data set.
  }
  const db = defaultMockDb();
  window.localStorage.setItem(MOCK_DB_KEY, JSON.stringify(db));
  return db;
};

const saveMockDb = (db: any) => {
  if (typeof window !== "undefined") {
    window.localStorage.setItem(MOCK_DB_KEY, JSON.stringify(db));
  }
};

const demoSession = () => ({
  access_token: "demo-access-token",
  token_type: "bearer",
  expires_in: 3600,
  refresh_token: "demo-refresh-token",
  user: {
    id: "demo-user",
    email: "demo@eduport.tn",
    role: "authenticated",
    app_metadata: {},
    user_metadata: { prenom: "Nour", nom: "Ben Ali" },
  },
});

const loadMockSession = () => {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(MOCK_SESSION_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
};

const saveMockSession = (session: any) => {
  if (typeof window === "undefined") return;
  if (session) window.localStorage.setItem(MOCK_SESSION_KEY, JSON.stringify(session));
  else window.localStorage.removeItem(MOCK_SESSION_KEY);
};

const authListeners: Array<(event: string, session: any) => void> = [];

const notifyAuthListeners = (event: string, session: any) => {
  authListeners.forEach((listener) => listener(event, session));
};

const cloneRows = (rows: any[]) => rows.map((row) => JSON.parse(JSON.stringify(row)));

const matchesFilters = (row: any, filters: Array<[string, any]>) => filters.every(([key, value]) => row?.[key] === value);

const applyOrdering = (rows: any[], orderings: Array<{ column: string; ascending: boolean }>) => {
  const sorted = [...rows];
  sorted.sort((left, right) => {
    for (const ordering of orderings) {
      const a = left?.[ordering.column];
      const b = right?.[ordering.column];
      if (a === b) continue;
      const direction = ordering.ascending ? 1 : -1;
      if (a == null) return 1 * direction;
      if (b == null) return -1 * direction;
      return a > b ? 1 * direction : -1 * direction;
    }
    return 0;
  });
  return sorted;
};

class MockQueryBuilder {
  private mode: "select" | "insert" | "update" | "delete" = "select";
  private payload: any = null;
  private filters: Array<[string, any]> = [];
  private orderings: Array<{ column: string; ascending: boolean }> = [];
  private singleResult = false;

  constructor(private table: string) {}

  select() {
    if (this.mode !== "insert") this.mode = "select";
    return this;
  }

  insert(values: any) {
    this.mode = "insert";
    this.payload = values;
    return this;
  }

  update(values: any) {
    this.mode = "update";
    this.payload = values;
    return this;
  }

  delete() {
    this.mode = "delete";
    return this;
  }

  eq(column: string, value: any) {
    this.filters.push([column, value]);
    return this;
  }

  order(column: string, options?: { ascending?: boolean }) {
    this.orderings.push({ column, ascending: options?.ascending ?? true });
    return this;
  }

  maybeSingle() {
    this.singleResult = true;
    return this;
  }

  single() {
    this.singleResult = true;
    return this;
  }

  then(onFulfilled: any, onRejected: any) {
    return this.execute().then(onFulfilled, onRejected);
  }

  private execute() {
    try {
      const db = loadMockDb();
      const rows = (db as any)[this.table] ?? [];
      const filteredRows = cloneRows(rows.filter((row: any) => matchesFilters(row, this.filters)));

      if (this.mode === "insert") {
        const insertedRows = (Array.isArray(this.payload) ? this.payload : [this.payload]).map((value) => ({
          id: `mock-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          created_at: new Date().toISOString(),
          ...value,
        }));
        (db as any)[this.table] = [...rows, ...insertedRows];
        saveMockDb(db);
        return Promise.resolve({ data: this.singleResult ? insertedRows[0] ?? null : insertedRows, error: null });
      }

      if (this.mode === "update") {
        const updatedRows = rows.map((row: any) => (matchesFilters(row, this.filters) ? { ...row, ...this.payload } : row));
        (db as any)[this.table] = updatedRows;
        saveMockDb(db);
        return Promise.resolve({ data: this.singleResult ? updatedRows.find((row: any) => matchesFilters(row, this.filters)) ?? null : updatedRows, error: null });
      }

      if (this.mode === "delete") {
        const remainingRows = rows.filter((row: any) => !matchesFilters(row, this.filters));
        (db as any)[this.table] = remainingRows;
        saveMockDb(db);
        return Promise.resolve({ data: null, error: null });
      }

      const orderedRows = this.orderings.length ? applyOrdering(filteredRows, this.orderings) : filteredRows;
      return Promise.resolve({ data: this.singleResult ? orderedRows[0] ?? null : orderedRows, error: null });
    } catch (error: any) {
      return Promise.resolve({ data: null, error });
    }
  }
}

const createMockSupabase = () => {
  const sessionState = { current: loadMockSession() ?? null };

  const setSession = (session: any) => {
    sessionState.current = session;
    saveMockSession(session);
    notifyAuthListeners(session ? "SIGNED_IN" : "SIGNED_OUT", session);
    return session;
  };

  const mockAuth = {
    onAuthStateChange(callback: (event: string, session: any) => void) {
      authListeners.push(callback);
      return {
        data: {
          subscription: {
            unsubscribe: () => {
              const index = authListeners.indexOf(callback);
              if (index >= 0) authListeners.splice(index, 1);
            },
          },
        },
      };
    },
    getSession: async () => ({ data: { session: sessionState.current }, error: null }),
    signInWithPassword: async () => ({ data: { session: setSession(demoSession()) }, error: null }),
    signUp: async () => ({ data: { session: setSession(demoSession()) }, error: null }),
    signOut: async () => {
      setSession(null);
      return { error: null };
    },
  };

  return {
    auth: mockAuth,
    from: (table: string) => new MockQueryBuilder(table),
    functions: {
      invoke: async (name: string, options?: { body?: any }) => {
        if (name === "document-agent" && options?.body?.requestId) {
          const db = loadMockDb();
          const request = (db.document_requests as any[]).find((row) => row.id === options.body.requestId);
          if (request) {
            Object.assign(request, {
              statut: "approuve",
              decision_ia: "Document genere en mode demo",
              pdf_url: "about:blank",
              reviewed_at: new Date().toISOString(),
            });
            saveMockDb(db);
          }
        }
        return { data: { ok: true }, error: null };
      },
    },
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: any = HAS_SUPABASE_CONFIG
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createMockSupabase();

export const hasSupabaseConfig = HAS_SUPABASE_CONFIG;