// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const FORCE_MOCK = import.meta.env.VITE_FORCE_MOCK === "true";

const HAS_SUPABASE_CONFIG = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) && !FORCE_MOCK;
const MOCK_DB_KEY = "eduport-mock-db";
const MOCK_SESSION_KEY = "eduport-mock-session";


const defaultMockDb = () => ({
  profiles: [
    { id: "demo-profile", user_id: "demo-user", prenom: "Nour", nom: "Ben Ali", email: "demo@eduport.tn", filiere: "GL", niveau: "L3", cin: "00000000", telephone: "+216 00 000 000", bio: "Mode demo local", date_naissance: "2002-04-20" },
    { id: "demo-student-2", user_id: "demo-student-2", prenom: "Karim", nom: "Mansouri", email: "karim.mansouri@eduport.tn", filiere: "GL", niveau: "L2", cin: "11111111", telephone: "+216 11 111 111", bio: "" },
    { id: "demo-student-3", user_id: "demo-student-3", prenom: "Fatma", nom: "Karray", email: "fatma.karray@eduport.tn", filiere: "RT", niveau: "L3", cin: "22222222", telephone: "+216 22 222 222", bio: "" },
    { id: "demo-student-4", user_id: "demo-student-4", prenom: "Ahmed", nom: "Belhaj", email: "ahmed.belhaj@eduport.tn", filiere: "GL", niveau: "L1", cin: "33333333", telephone: "+216 33 333 333", bio: "" },
    { id: "demo-student-5", user_id: "demo-student-5", prenom: "Leila", nom: "Jaziri", email: "leila.jaziri@eduport.tn", filiere: "RT", niveau: "L2", cin: "44444444", telephone: "+216 44 444 444", bio: "" },
    { id: "demo-prof-1", user_id: "demo-prof-1", prenom: "Amina", nom: "Trabelsi", email: "amina.trabelsi@eduport.tn", filiere: "GL", niveau: "Professeur", bureau: "B12" },
    { id: "demo-prof-2", user_id: "demo-prof-2", prenom: "Youssef", nom: "Haddad", email: "youssef.haddad@eduport.tn", filiere: "RT", niveau: "Professeur", bureau: "C04" },
    { id: "demo-admin", user_id: "demo-admin", prenom: "Sara", nom: "Mansouri", email: "sara.mansouri@eduport.tn", filiere: "GL", niveau: "Admin" },
  ],
  user_roles: [
    { user_id: "demo-user", role: "student" },
    { user_id: "demo-student-2", role: "student" },
    { user_id: "demo-student-3", role: "student" },
    { user_id: "demo-student-4", role: "student" },
    { user_id: "demo-student-5", role: "student" },
    { user_id: "demo-prof-1", role: "professor" },
    { user_id: "demo-prof-2", role: "professor" },
    { user_id: "demo-admin", role: "admin" },
  ],
  subjects: [
    { id: "alg-301", nom: "Algorithmique", code: "ALG301", coefficient: 3, semestre: "S5", filiere: "GL", professor_id: "demo-prof-1", professor: { id: "demo-prof-1", prenom: "Amina", nom: "Trabelsi" } },
    { id: "bdd-302", nom: "Bases de données", code: "BDD302", coefficient: 2, semestre: "S5", filiere: "GL", professor_id: "demo-prof-1", professor: { id: "demo-prof-1", prenom: "Amina", nom: "Trabelsi" } },
    { id: "rnv-303", nom: "Réseaux", code: "RNV303", coefficient: 2, semestre: "S5", filiere: "RT", professor_id: "demo-prof-2", professor: { id: "demo-prof-2", prenom: "Youssef", nom: "Haddad" } },
    { id: "math-201", nom: "Mathématiques", code: "MATH201", coefficient: 3, semestre: "S4", filiere: "GL", professor_id: null, professor: null },
    { id: "sys-401", nom: "Systèmes d'exploitation", code: "SYS401", coefficient: 2, semestre: "S5", filiere: "RT", professor_id: "demo-prof-2", professor: { id: "demo-prof-2", prenom: "Youssef", nom: "Haddad" } },
  ],
  grades: [
    { id: "grade-1", student_id: "demo-profile", note: 17.5, poids: 1, type: "DS", date_evaluation: "2026-03-10", subjects: { id: "alg-301", nom: "Algorithmique", code: "ALG301", coefficient: 3, semestre: "S5", filiere: "GL" } },
    { id: "grade-2", student_id: "demo-profile", note: 14.8, poids: 1, type: "TP", date_evaluation: "2026-03-15", subjects: { id: "bdd-302", nom: "Bases de données", code: "BDD302", coefficient: 2, semestre: "S5", filiere: "GL" } },
    { id: "grade-3", student_id: "demo-profile", note: 13.2, poids: 1, type: "Examen", date_evaluation: "2026-03-22", subjects: { id: "rnv-303", nom: "Réseaux", code: "RNV303", coefficient: 2, semestre: "S5", filiere: "GL" } },
    { id: "grade-4", student_id: "demo-student-2", note: 15.5, poids: 1, type: "DS", date_evaluation: "2026-03-10", subjects: { id: "alg-301", nom: "Algorithmique", code: "ALG301", coefficient: 3, semestre: "S5", filiere: "GL" } },
    { id: "grade-5", student_id: "demo-student-2", note: 12.0, poids: 1, type: "Examen", date_evaluation: "2026-03-20", subjects: { id: "bdd-302", nom: "Bases de données", code: "BDD302", coefficient: 2, semestre: "S5", filiere: "GL" } },
    { id: "grade-6", student_id: "demo-student-3", note: 18.0, poids: 1, type: "DS", date_evaluation: "2026-03-15", subjects: { id: "rnv-303", nom: "Réseaux", code: "RNV303", coefficient: 2, semestre: "S5", filiere: "RT" } },
    { id: "grade-7", student_id: "demo-student-3", note: 16.5, poids: 1, type: "TP", date_evaluation: "2026-03-18", subjects: { id: "sys-401", nom: "Systèmes d'exploitation", code: "SYS401", coefficient: 2, semestre: "S5", filiere: "RT" } },
    { id: "grade-8", student_id: "demo-student-4", note: 9.5, poids: 1, type: "DS", date_evaluation: "2026-03-10", subjects: { id: "math-201", nom: "Mathématiques", code: "MATH201", coefficient: 3, semestre: "S4", filiere: "GL" } },
    { id: "grade-9", student_id: "demo-student-5", note: 14.0, poids: 1, type: "Examen", date_evaluation: "2026-03-22", subjects: { id: "rnv-303", nom: "Réseaux", code: "RNV303", coefficient: 2, semestre: "S5", filiere: "RT" } },
  ],
  schedule: [
    { id: "sched-1", filiere: "GL", jour: 1, heure_debut: "08:00:00", heure_fin: "10:00:00", type_seance: "CM", salle: "A101", subject_id: "alg-301", subjects: { nom: "Algorithmique", code: "ALG301" } },
    { id: "sched-2", filiere: "GL", jour: 1, heure_debut: "10:30:00", heure_fin: "12:30:00", type_seance: "TD", salle: "B204", subject_id: "bdd-302", subjects: { nom: "Bases de données", code: "BDD302" } },
    { id: "sched-3", filiere: "GL", jour: 3, heure_debut: "14:00:00", heure_fin: "16:00:00", type_seance: "TP", salle: "Lab 2", subject_id: "rnv-303", subjects: { nom: "Réseaux", code: "RNV303" } },
    { id: "sched-4", filiere: "RT", jour: 2, heure_debut: "08:00:00", heure_fin: "10:00:00", type_seance: "CM", salle: "C201", subject_id: "rnv-303", subjects: { nom: "Réseaux", code: "RNV303" } },
    { id: "sched-5", filiere: "RT", jour: 4, heure_debut: "10:30:00", heure_fin: "12:30:00", type_seance: "TP", salle: "Lab 3", subject_id: "sys-401", subjects: { nom: "Systèmes d'exploitation", code: "SYS401" } },
  ],
  document_requests: [
    {
      id: "doc-1",
      student_id: "demo-profile",
      type: "attestation_inscription",
      motif: "Pour mon stage",
      statut: "en_attente",
      created_at: new Date().toISOString(),
      decision_ia: null,
      pdf_url: null,
      reviewed_at: null,
      profiles: { prenom: "Nour", nom: "Ben Ali", filiere: "GL" },
    },
  ],
});

const loadMockDb = () => {
  if (typeof window === "undefined") return defaultMockDb();
  try {
    const raw = window.localStorage.getItem(MOCK_DB_KEY);
    if (raw) return JSON.parse(raw);
  } catch {
    // Fall through to the default data set.
  }
  const db = defaultMockDb();
  window.localStorage.setItem(MOCK_DB_KEY, JSON.stringify(db));
  return db;
};

const saveMockDb = (db: any) => {
  if (typeof window !== "undefined") {
    window.localStorage.setItem(MOCK_DB_KEY, JSON.stringify(db));
  }
};

const makeSession = (userId: string, email: string) => ({
  access_token: `demo-token-${userId}`,
  token_type: "bearer",
  expires_in: 3600,
  refresh_token: `demo-refresh-${userId}`,
  user: { id: userId, email, role: "authenticated", app_metadata: {}, user_metadata: {} },
});


const loadMockSession = () => {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(MOCK_SESSION_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
};

const saveMockSession = (session: any) => {
  if (typeof window === "undefined") return;
  if (session) window.localStorage.setItem(MOCK_SESSION_KEY, JSON.stringify(session));
  else window.localStorage.removeItem(MOCK_SESSION_KEY);
};

const authListeners: Array<(event: string, session: any) => void> = [];

const notifyAuthListeners = (event: string, session: any) => {
  authListeners.forEach((listener) => listener(event, session));
};

const cloneRows = (rows: any[]) => rows.map((row) => JSON.parse(JSON.stringify(row)));

const matchesFilters = (row: any, filters: Array<[string, any]>) => filters.every(([key, value]) => row?.[key] === value);

const applyOrdering = (rows: any[], orderings: Array<{ column: string; ascending: boolean }>) => {
  const sorted = [...rows];
  sorted.sort((left, right) => {
    for (const ordering of orderings) {
      const a = left?.[ordering.column];
      const b = right?.[ordering.column];
      if (a === b) continue;
      const direction = ordering.ascending ? 1 : -1;
      if (a == null) return 1 * direction;
      if (b == null) return -1 * direction;
      return a > b ? 1 * direction : -1 * direction;
    }
    return 0;
  });
  return sorted;
};

class MockQueryBuilder {
  private mode: "select" | "insert" | "update" | "delete" = "select";
  private payload: any = null;
  private filters: Array<[string, any]> = [];
  private orderings: Array<{ column: string; ascending: boolean }> = [];
  private singleResult = false;

  constructor(private table: string) {}

  select() {
    if (this.mode !== "insert") this.mode = "select";
    return this;
  }

  insert(values: any) {
    this.mode = "insert";
    this.payload = values;
    return this;
  }

  update(values: any) {
    this.mode = "update";
    this.payload = values;
    return this;
  }

  delete() {
    this.mode = "delete";
    return this;
  }

  eq(column: string, value: any) {
    this.filters.push([column, value]);
    return this;
  }

  order(column: string, options?: { ascending?: boolean }) {
    this.orderings.push({ column, ascending: options?.ascending ?? true });
    return this;
  }

  maybeSingle() {
    this.singleResult = true;
    return this;
  }

  single() {
    this.singleResult = true;
    return this;
  }

  then(onFulfilled: any, onRejected: any) {
    return this.execute().then(onFulfilled, onRejected);
  }

  private execute() {
    try {
      const db = loadMockDb();
      const rows = (db as any)[this.table] ?? [];
      const filteredRows = cloneRows(rows.filter((row: any) => matchesFilters(row, this.filters)));

      if (this.mode === "insert") {
        const insertedRows = (Array.isArray(this.payload) ? this.payload : [this.payload]).map((value) => ({
          id: `mock-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          created_at: new Date().toISOString(),
          ...value,
        }));
        (db as any)[this.table] = [...rows, ...insertedRows];
        saveMockDb(db);
        return Promise.resolve({ data: this.singleResult ? insertedRows[0] ?? null : insertedRows, error: null });
      }

      if (this.mode === "update") {
        const updatedRows = rows.map((row: any) => (matchesFilters(row, this.filters) ? { ...row, ...this.payload } : row));
        (db as any)[this.table] = updatedRows;
        saveMockDb(db);
        return Promise.resolve({ data: this.singleResult ? updatedRows.find((row: any) => matchesFilters(row, this.filters)) ?? null : updatedRows, error: null });
      }

      if (this.mode === "delete") {
        const remainingRows = rows.filter((row: any) => !matchesFilters(row, this.filters));
        (db as any)[this.table] = remainingRows;
        saveMockDb(db);
        return Promise.resolve({ data: null, error: null });
      }

      const orderedRows = this.orderings.length ? applyOrdering(filteredRows, this.orderings) : filteredRows;
      return Promise.resolve({ data: this.singleResult ? orderedRows[0] ?? null : orderedRows, error: null });
    } catch (error: any) {
      return Promise.resolve({ data: null, error });
    }
  }
}

const createMockSupabase = () => {
  const sessionState = { current: loadMockSession() ?? null };

  const setSession = (session: any) => {
    sessionState.current = session;
    saveMockSession(session);
    notifyAuthListeners(session ? "SIGNED_IN" : "SIGNED_OUT", session);
    return session;
  };

  const mockAuth = {
    onAuthStateChange(callback: (event: string, session: any) => void) {
      authListeners.push(callback);
      return {
        data: {
          subscription: {
            unsubscribe: () => {
              const index = authListeners.indexOf(callback);
              if (index >= 0) authListeners.splice(index, 1);
            },
          },
        },
      };
    },
    getSession: async () => ({ data: { session: sessionState.current }, error: null }),
    signInWithPassword: async ({ email }: { email: string; password: string }) => {
      const db = loadMockDb();
      const profile = (db.profiles as any[]).find((p: any) => p.email === email);
      if (!profile) return { data: { session: null }, error: { message: "Email ou mot de passe incorrect." } };
      return { data: { session: setSession(makeSession(profile.user_id, profile.email)) }, error: null };
    },
    signUp: async ({ email }: { email: string; password: string }) => {
      const db = loadMockDb();
      const profile = (db.profiles as any[]).find((p: any) => p.email === email);
      const userId = profile?.user_id ?? "demo-user";
      const userEmail = profile?.email ?? email;
      return { data: { session: setSession(makeSession(userId, userEmail)) }, error: null };
    },
    signOut: async () => {
      setSession(null);
      return { error: null };
    },
  };

  return {
    auth: mockAuth,
    from: (table: string) => new MockQueryBuilder(table),
    functions: {
      invoke: async (name: string, options?: { body?: any }) => {
        if (name === "document-agent" && options?.body?.requestId) {
          const db = loadMockDb();
          const request = (db.document_requests as any[]).find((row) => row.id === options.body.requestId);
          if (request) {
            Object.assign(request, { 
              statut: "en_attente", 
              decision_ia: "PDF généré (en attente d'approbation manuelle)", 
              pdf_url: "about:blank" 
            });
            saveMockDb(db);
          }
        }
        if (name === "admin-create-user" && options?.body) {
          const { email, role, prenom, nom, filiere, niveau, bureau } = options.body;
          const db = loadMockDb();
          const newId = `mock-user-${Date.now()}`;
          (db.profiles as any[]).push({ id: newId, user_id: newId, prenom, nom, email, filiere, niveau: role === "professor" ? "Professeur" : niveau, bureau: bureau || null, cin: null, telephone: null, bio: null, date_naissance: null, created_at: new Date().toISOString() });
          (db.user_roles as any[]).push({ user_id: newId, role });
          saveMockDb(db);
          return { data: { ok: true, userId: newId }, error: null };
        }
        return { data: { ok: true }, error: null };
      },
    },
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: any = HAS_SUPABASE_CONFIG
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createMockSupabase();

export const hasSupabaseConfig = HAS_SUPABASE_CONFIG;